### ISSUE TITLE
Make image publish on push

### ISSUE THREAD

**Issue by o-az** [v3xlabs/enstate#63]
Would you be open to changing the release flow to be on push to master without having to manually issue a tag?

**Comment by svemat01** [comment]
Hey!
This should already have been introduced a couple of days ago with PR #52 and be available with `edge` tag. Tags are also available for specific git commits with the `sha-GITHASH` tag.

I believe this resolves your issue but feel free to reopen if I'm mistaken 😊

**Comment by o-az** [comment]
> Hey! This should already have been introduced a couple of days ago with PR #52 and be available with `edge` tag. Tags are also available for specific git commits with the `sha-GITHASH` tag.
> 
> I believe this resolves your issue but feel free to reopen if I'm mistaken 😊

For major versions, are they only published manually?

**Comment by svemat01** [comment]
Yes, only the edge and sha-GITHASH tags are published on commit push. The semver tags are published when a release is made by us manually.
