### ISSUE TITLE
bulk max length

### ISSUE THREAD

**Issue by o-az** [v3xlabs/enstate#68]
Curious about the 10 limit in bulk endpoints. Any reason it's set to 10?

**Comment by Antony1060** [comment]
We just felt like this is a good compromise not to overload the actual server.

**Comment by lucemans** [comment]
This was just recently introduced in https://github.com/v3xlabs/enstate/pull/98

You are now able to customize the max bulk limit on a per-instance basis using the `MAX_BULK_SIZE` env variable.

Hope this helps!
